name: Deploy Website

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test website
        run: |
          test -f index.html
          test -f style.css
          test -f script.js
          echo "Website files found successfully"

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build / Package website
        run: |
          mkdir -p dist
          cp index.html dist/
          cp style.css dist/
          cp script.js dist/
          echo "Website packaged successfully"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: website-build
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: website-build
          path: dist

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::264053230266:role/GitHubActions-DevOpsWebsite
          aws-region: eu-north-1

      - name: Deploy website to S3
        run: |
          aws s3 sync dist/ s3://devops-cicd-website-shubham-5199 --delete
